### ISSUE TITLE
Fix DRY issues in CSS

### ISSUE THREAD

**Issue by chloetruax** [gsavickas/FirstProjectWeek1#6]
Make sure you're building reusable classes. For instance, you have the declaraton for `flex-direction: column` in a couple places where you should create a single class to help with those. You also have: 
``` CSS
}
h3{
    text-shadow: -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px 1px 0 #000,
    1px 1px 0 #000;
}
h2{
    text-shadow: -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px 1px 0 #000,
    1px 1px 0 #000;
}
h1{
    text-shadow: -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px 1px 0 #000,
    1px 1px 0 #000;
}
```

which since they're all the same declarations should be simplified to: 
``` CSS
}
h1, h2, h3{
    text-shadow: -1px -1px 0 #000,
    1px -1px 0 #000,
    -1px 1px 0 #000,
    1px 1px 0 #000;
}
```
